// v616：ToDo（スマホ）＝今日の手帳（10行目に線・＋αは何件でも・毎日のいつもの行・前の日の残り・ふりかえり・学んだ事・タスクの画面）
const T = require('../lib/head.js')();
const { w, c, sleep, setWH, $, $$ } = T;
T.run(async () => {
  T.login(); w._cvNew = () => w._cvOn(); // v620で止めた新しい入力（コードは残す）を確かめる
  w._evLoadedUid = 'x';
  w.state.members = [{ id: 'a1', lastName: '佐藤', firstName: '花', title: 'マケ', parentId: '', mapType: 'both', trainee: true }];
  const Tk = (id, d, t, x) => Object.assign({ id, date: d, time: '', title: t, type: 'task', done: false, memberIds: [], priority: 'normal', createdAt: '2026-10-14T0' + id.length + ':00:00Z' }, x || {});
  w.state.events = [Tk('t1', '2026-10-14', 'タスク報告', { done: true }), Tk('t2', '2026-10-14', 'ST報告'), Tk('y1', '2026-10-13', '名刺つくる'), Tk('y2', '2026-10-12', 'PA準備'),
    { id: 'e1', date: '2026-10-14', time: '19:00', title: 'ST', type: 'event', memberIds: [] }];
  for (let i = 0; i < 11; i++) w.state.events.push(Tk('w' + i, '2026-10-11', 'x' + i, { done: true }));
  for (let i = 0; i < 10; i++) w.state.events.push(Tk('v' + i, '2026-10-13', 'v' + i, { done: true }));
  setWH(390, 844);
  w.switchView('events'); w.setEventsMode('agenda'); await sleep(50);
  const L = $('#evAgendaList'), rows = () => $$('#evAgendaList .dpr0[data-eid]');
  console.log('=== ① 今日の手帳 ===');
  c('スマホのToDo＝今日の手帳（古い入力欄は隠れる）', !!$('.dph') && w.document.body.classList.contains('dp-on') && $('.dph').textContent.indexOf('10/14') >= 0 && $('.dph').textContent.indexOf('今日やるべき事') >= 0);
  c('毎日のいつもの行「計画立案する」が1行目に自動で入る', rows()[0].textContent.indexOf('計画立案する') >= 0 && rows()[0].textContent.indexOf('毎日') >= 0 && w.state.events.filter(e => e.dpDaily).length === 1);
  w.renderAgenda(); c('何度開いても1つだけ', w.state.events.filter(e => e.dpDaily === '計画立案する').length === 1);
  c('行に番号・チェック・A/B/C', rows().length === 3 && rows()[1].querySelector('.n').textContent === '2' && !!rows()[1].querySelector('.ck') && rows()[1].querySelector('.p').textContent === 'B');
  c('書いた数のメーター（3/10・やった1・あと7件）', $('.dpg').textContent.indexOf('3') >= 0 && $('.dpg').textContent.indexOf('/ 10件') >= 0 && $('.dpg').textContent.indexOf('やった 1') >= 0 && $('.dpg').textContent.indexOf('あと7件') >= 0 && $$('.dpbar i').length === 10);
  c('10行目まで空き行（赤っぽく）＋10件の線', $$('.dpr0.need').length === 7 && $('.dpten').textContent.indexOf('今日の10件') >= 0);
  c('書く行は1つ（Enterで次の行へ）', !!$('#dpIn'));
  console.log('=== ② 行に書く ===');
  $('#dpIn').value = 'ゆうやさんにマッチング'; w.dpAdd(); await sleep(5);
  c('行が増える・今日の日付', rows().length === 4 && w.state.events.find(e => e.title === 'ゆうやさんにマッチング').date === '2026-10-14' && w.state.events.find(e => e.title === 'ゆうやさんにマッチング').type === 'task');
  c('入力欄は空に戻る', $('#dpIn').value === '');
  const ev = new w.KeyboardEvent('keydown', { key: 'Enter' }); $('#dpIn').value = '例え話'; $('#dpIn').dispatchEvent(ev); w.dpKey(Object.assign(ev, {}));
  c('Enterでも追加（変換中のEnterは無視）', !!w.state.events.find(e => e.title === '例え話'));
  const ime = { isComposing: true, key: 'Enter', keyCode: 229, preventDefault() {} }; $('#dpIn').value = 'へんかん'; w.dpKey(ime);
  c('変換確定のEnterでは追加しない', !w.state.events.find(e => e.title === 'へんかん'));
  $('#dpIn').value = '';
  for (let i = 0; i < 5; i++) w.dpAdd('タスク' + i);
  c('10件そろう→「そろいました」', rows().length === 10 && $('.dpg').textContent.indexOf('10件 そろいました') >= 0 && !$('.dpr0.need'));
  w.dpAdd('もっと1'); w.dpAdd('もっと2');
  c('＋αは何件でも（11・12行目の番号は金色）', rows().length === 12 && rows()[10].querySelector('.n').classList.contains('au') && rows()[11].querySelector('.n').textContent === '12');
  c('メーターは「10件 ＋2」（金）・バーが伸びる', $('.dpg em.au') && $('.dpg em.au').textContent.indexOf('＋2') >= 0 && $$('.dpbar i').length === 12 && $$('.dpbar i.x').length === 2);
  c('10行目の後に「ここからは＋α」の線', $('.dpten.ok') && $('.dpten.ok').textContent.indexOf('＋α') >= 0);
  c('1週間の記録：今日は12✦（金）', $('.dpwk .cur').textContent.indexOf('12✦') >= 0 && $('.dpwk .cur').classList.contains('au'));
  c('10件書いた日の連続（10/13・10/14 → 2日。10/12は0件）', $('.dpst').textContent.indexOf('2日連続') >= 0, $('.dpst').textContent);
  console.log('=== ③ チェック・優先・タスクの画面 ===');
  const id = w.state.events.find(e => e.title === '例え話').id;
  w.dpDone(id); await sleep(300); c('チェックで完了（行に残る・取り消し線）', w.state.events.find(e => e.id === id).done && !!$('.dpr0.dn[data-eid="' + id + '"]'));
  w.dpPrio(id); c('A/B/Cを押すと切り替わる（B→C）', w.state.events.find(e => e.id === id).priority === 'low' && $('.dpr0[data-eid="' + id + '"] .p').textContent === 'C');
  w.dpPrio(id); c('C→A', w.state.events.find(e => e.id === id).priority === 'high');
  w.openEventActions(id); await sleep(5);
  c('行を押すとタスクの画面', !!$('#tkPg') && $('#tkTitle').value === '例え話');
  w.openTimePad('tkT'); w.tpKey('1'); w.tpKey('8'); w.tpKey('00'); await sleep(450);
  c('時刻は今の数字パッド（任意）', w.state.events.find(e => e.id === id).time === '18:00' && $('#tkT').value === '18:00');
  w.tkTimeClear(); c('時刻を外せる', !w.state.events.find(e => e.id === id).time);
  w.tkWho('a1'); c('だれの（メンバー）', w.state.events.find(e => e.id === id).memberIds.join() === 'a1');
  w.tkPrio('low'); c('優先 C', w.state.events.find(e => e.id === id).priority === 'low');
  w.tkDate('2026-10-15'); c('やる日を明日に', w.state.events.find(e => e.id === id).date === '2026-10-15');
  w.tkClose(); await sleep(5);
  c('今日の手帳から明日へ移った', !$('.dpr0[data-eid="' + id + '"]'));
  console.log('=== ④ 前の日の残り・ふりかえり ===');
  c('前の日の残り 2件', $$('.dpcard')[0].textContent.indexOf('前の日の残り 2件') >= 0);
  w.dpMoveAll('left', '2026-10-14'); c('今日に入れる', w.state.events.find(e => e.id === 'y1').date === '2026-10-14' && w.state.events.find(e => e.id === 'y2').date === '2026-10-14' && !$('.dpcard b').textContent.match(/前の日の残り/));
  w.dpGo(-1); await sleep(5);
  c('前の日へ（‹）・過ぎた日のふりかえりは「今日へ」', $('.dph').textContent.indexOf('10/13') >= 0 && $('.dph').textContent.indexOf('昨日のやるべき事') >= 0 && !$('.dpsg'));
  w.dpGo(0);
  w.dpMove('y1', '2026-10-15'); c('1件ずつ明日へ', w.state.events.find(e => e.id === 'y1').date === '2026-10-15');
  w.dpMoveAll('day', '2026-10-20'); const left = w.state.events.filter(e => e.type === 'task' && e.date === '2026-10-14' && !e.done);
  c('やっていない分をまとめて選んだ日へ', left.length === 0 && w.state.events.find(e => e.id === 'y2').date === '2026-10-20');
  console.log('=== ⑤ 学んだ事・毎日のいつもの行・すべてのタスク ===');
  w.dpLearn('ストーリーは短く'); await sleep(900);
  c('今日学んだ事を保存', (w._p2().learn || {})['2026-10-14'] === 'ストーリーは短く');
  w.dpDailyEdit(); $('#dpDlIn').value = 'ST報告'; w.dpDailyAdd();
  c('毎日のいつもの行を足す', w._dpDaily().join() === '計画立案する,ST報告' && w.state.events.filter(e => e.dpDaily === 'ST報告' && e.date === '2026-10-14').length === 1);
  w.dpDailyDel(1); w._p2SheetClose('dpDlOv');
  w.dpAllTasks(true); c('すべてのタスク（今までのToDo）＋手帳に戻るボタン', !w.document.body.classList.contains('dp-on') && !!$('.dpback'));
  w.cvBack(); c('‹戻るで手帳へ', w.document.body.classList.contains('dp-on') && !!$('.dph'));
  w.cvAdd('agenda'); c('右下「＋ ToDo」', $('#evAgenda .cv-add').textContent.indexOf('ToDo') >= 0);
  console.log('=== ⑥ 横向き・PC ===');
  setWH(844, 390); w._uxSync(); w.renderAgenda(); await sleep(10);
  c('横向き：右にタイムスケジュール（その日の予定）', !!$('.dpr .dpts') && $('.dpr').textContent.indexOf('19:00 ST') >= 0);
  setWH(1400, 900); w._uxSync(); w.setEventsMode('agenda'); await sleep(20);
  c('PCは今までのToDo', !$('.dph') && !w.document.body.classList.contains('dp-on'));
});
