// v614：予定の入力＝1枚（足す・直す共通）
const T = require('../lib/head.js')();
const { w, c, sleep, setWH, $, $$ } = T;
T.run(async () => {
  T.login();
  w.state.members = [{ id: 'a1', lastName: '佐藤', firstName: '花', title: '', parentId: '', mapType: 'both', trainee: true }, { id: 'a2', lastName: '田中', firstName: '健', title: 'B1', parentId: '', mapType: 'both' }, { id: 'a3', lastName: '鈴木', firstName: '一郎', title: 'B2', parentId: '', mapType: 'both' }];
  w.state.categories = [{ id: 'c1', name: 'CT', color: '#7C6CF2' }, { id: 'c2', name: 'ST', color: '#2BA3E0' }];
  const E = (id, d, tm, t, x) => Object.assign({ id, date: d, time: tm, title: t, type: 'event', memberIds: [], createdAt: d + 'T00:00:00' }, x || {});
  w.state.events = [E('e1', '2026-10-13', '19:00', 'CT 鈴木さん', { endTime: '20:00', memberIds: ['a1'], memberId: 'a1', vis: 'both', place: 'オンライン', categoryId: 'c1', color: '#7C6CF2', remindBefore: 30 }),
    E('e2', '2026-10-20', '', '合宿', { endDate: '2026-10-22', allDay: true }), E('t1', '2026-10-14', '', '名簿を送る', { type: 'task' })];
  w._evTpl = [{ id: 'tp1', type: 'event', name: 'ST', defaultTime: '20:00', durationMin: 60, categoryId: 'c2', useCount: 1, notifyOffset: 30 }];
  setWH(390, 844);
  w.switchView('events'); w.setEventsMode('calendar'); await sleep(60);
  const ev = id => w.state.events.find(e => e.id === id);
  const pad = async (a, b) => { w.openTimePad('wnT'); for (const k of a) w.tpKey(k); for (const k of b) w.tpKey(k); await sleep(450); };
  console.log('=== ① 足す：長押し・＋予定で開く 1枚 ===');
  w.openEventAddDate('2026-10-15'); await sleep(10);
  c('1枚の画面（3ステップではない）', !!$('#efPg') && $('#efPg .efh').textContent.indexOf('予定を足す') >= 0 && !$('#eventModal').classList.contains('open'));
  c('名前が一番上', !!$('#efTitle') && $('#efPg').innerHTML.indexOf('efTitle') < $('#efPg').innerHTML.indexOf('efd'));
  c('いつもの予定・最近の予定のボタンは出さない', $('#efPg').textContent.indexOf('最近の予定') < 0 && !$('.eftl'));
  c('日付は1行（押した日）＋「日付を変える」「＋連日」', $('.efd').textContent.indexOf('10/15（木）') >= 0 && $('.efd').textContent.indexOf('明日') >= 0 && $('.efd').textContent.indexOf('日付を変える') >= 0 && !$('.efdi'));
  c('時刻は「開始〜終了」＋終日', !!$('#wnT') && !!$('#wnTE') && $('.wnt .ad').textContent === '終日');
  c('だれと＝検索＋リスト（チェック）', !!$('#efQ') && $$('#efWhoLs .efr').length >= 1 && !!$('#efWhoLs .efr i'));
  c('人を選ぶまで出すカレンダーは出ない', !$('.efv'));
  c('色・通知・場所メモ・繰り返しの行', ['色（カテゴリ）', '通知', '場所・メモ', '繰り返し'].every(k => $('.efa').textContent.indexOf(k) >= 0));
  c('右下は保存・左下はキャンセル', $('#efPg .ux-nx').textContent.indexOf('保存') >= 0 && $('#efPg .ux-bk').textContent.indexOf('キャンセル') >= 0);
  $('#efTitle').value = '佐藤CT'; w.efTitleIn('佐藤CT');
  await pad(['1', '9', '00'], ['2', '0', '00']);
  c('時刻は今の数字パッド（19:00〜20:00）', $('#wnT').value === '19:00' && $('#wnTE').value === '20:00' && w._ef.o.time === '19:00' && w._ef.o.end === '20:00');
  c('名前は描き直しても残る', $('#efTitle').value === '佐藤CT');
  w.efQ('鈴木'); c('名前でさがす', $('#efWhoLs').textContent.indexOf('鈴木 一郎') >= 0 && $('#efWhoLs').textContent.indexOf('佐藤') < 0);
  w.efWho('a1');
  c('選ぶと上に名前・リストに✓・検索はリセット', $('.efsel').textContent.indexOf('佐藤 花') >= 0 && !!$('#efWhoLs .efr.on') && $('#efQ').value === '');
  c('出すカレンダー3つ（メンバーだけ・自分だけ・両方）', $$('.efv span').length === 3 && $('.efv').textContent.indexOf('自分だけ') >= 0 && $('.efv span.on').textContent.indexOf('両方') === 0);
  w.efVis('self'); c('自分だけを選べる', $('.efv span.on').textContent.indexOf('自分だけ') === 0);
  w.efTgl('ntf'); c('通知はその場で開く', $$('.efa .op .efch span').length === 6);
  w.efRemind('30'); c('通知 30分前', w._ef.o.remind === '30' && $('.efa').textContent.indexOf('30分前') >= 0);
  w.efTgl('memo'); c('場所・メモもその場で入力欄', !!$('#efPlace') && !!$('#efMemo'));
  $('#efPlace').value = 'カフェ'; $('#efPlace').dispatchEvent(new w.Event('input')); w.efMemo('資料');
  let cb = null; const oS = w.openCategorySheet; w.openCategorySheet = (pick) => { cb = pick; };
  w.efCat(); c('色は今までのカテゴリ選択（編集もできる画面）を開く', cb === true && typeof w._catPickCb === 'function');
  w.openCategorySheet = oS; w.selectCategoryForEvent('c1');
  c('選んだカテゴリが入る', w._ef.o.cat === 'c1' && $('.efa').textContent.indexOf('CT') >= 0);
  const n0 = w.state.events.length; w.efSave(); await sleep(10);
  const ne = w.state.events.find(e => e.title === '佐藤CT');
  c('保存', w.state.events.length === n0 + 1 && ne && ne.date === '2026-10-15' && ne.time === '19:00' && ne.endTime === '20:00' && ne.memberIds.join() === 'a1' && ne.vis === 'self' && ne.remindBefore === 30 && ne.place === 'カフェ' && ne.memo === '資料' && ne.categoryId === 'c1' && ne.kind === 'CT');
  c('閉じて、その日が選ばれる', !$('#efPg') && w._calSelDate === '2026-10-15');
  console.log('=== ② 足す：日付を変える・連日・終日・テンプレ・繰り返し ===');
  w.openEventAddDate('2026-10-15'); w.efTgl('date');
  c('日付を変える→その場に日付欄', !!$('.efdi input[type=date]'));
  w.efDate('2026-10-16'); c('日付が変わる', w._ef.o.date === '2026-10-16' && $('.efd').textContent.indexOf('10/16（金）') >= 0);
  w.efTgl('end'); w.efEnd('2026-10-18'); c('連日', w._ef.o.endDate === '2026-10-18' && $('.efd').textContent.indexOf('〜 10/18') >= 0);
  w.efDate('2026-10-17'); c('連日は長さを保って移動', w._ef.o.endDate === '2026-10-19');
  w.efAllDay(); c('終日', w._ef.o.allDay && $('.wnt .ad').classList.contains('on'));
  w.efTgl('tpl'); c('⧉でテンプレ', !!$('.eftl') && $('.eftl').textContent.indexOf('ST') >= 0);
  w.efTpl('tp1'); c('テンプレで名前・時刻・色・通知', w._ef.o.title === 'ST' && w._ef.o.time === '20:00' && w._ef.o.end === '21:00' && w._ef.o.cat === 'c2' && w._ef.o.remind === '30' && !w._ef.o.allDay);
  w.efTgl('rep'); w.efRep('w'); c('繰り返し 毎週＋いつまで', w._ef.o.rep === 'w' && !!w._ef.o.repUntil && $('.efa').textContent.indexOf('毎週') >= 0);
  w.efEnd(''); w.efRep(''); w.efSave(); await sleep(10);
  const st = w.state.events.find(e => e.title === 'ST' && e.date === '2026-10-17');
  c('テンプレの印も入る', st && st.tplId === 'tp1' && w._evTpl[0].useCount === 2);
  w.openEventAddDate('2026-10-15'); w.efSave(); c('名前がないと保存しない', !!$('#efPg')); w.efClose();
  console.log('=== ③ 予定をタップ＝同じ1枚で直す（その場で保存） ===');
  w.openEventActions('e1'); await sleep(10);
  c('同じ1枚（中身が入っている）', !!$('#efPg') && $('#efTitle').value === 'CT 鈴木さん' && $('#wnT').value === '19:00' && $('.efsel').textContent.indexOf('佐藤 花') >= 0);
  c('「やった」ボタンはない', $('#efPg').textContent.indexOf('やった') < 0);
  c('右下「別の日にも入れる」・消す・今までの編集画面', $('#efPg .ux-nx').textContent.indexOf('別の日にも入れる') >= 0 && $('.efft').textContent.indexOf('この予定を消す') >= 0 && $('.efft').textContent.indexOf('今までの編集画面') >= 0);
  $('#efTitle').value = 'CT 鈴木 健太さん'; w.efTitleCh('CT 鈴木 健太さん'); c('名前を直す→保存', ev('e1').title === 'CT 鈴木 健太さん');
  await pad(['1', '8', '00'], ['2', '1', '30']);
  c('時刻を直す→保存', ev('e1').time === '18:00' && ev('e1').endTime === '21:30');
  w.efTgl('date'); w.efDate('2026-10-16'); c('日付を直す→保存', ev('e1').date === '2026-10-16');
  w.efWho('a2'); c('人を足す→保存', ev('e1').memberIds.join() === 'a1,a2');
  w.efVis('member'); c('メンバーだけ→保存', ev('e1').vis === 'member');
  w.efVis('self'); c('自分だけ→保存', ev('e1').vis === 'self');
  w.efWho('a1'); w.efWho('a2'); c('人を全部外す', ev('e1').memberIds.length === 0 && !$('.efv'));
  w.efTgl('ntf'); w.efRemind('60'); c('通知→保存', ev('e1').remindBefore === 60);
  w.efTgl('memo'); w.efPlace('会議室'); c('場所→保存', ev('e1').place === '会議室');
  w.efMemo('持ち物'); await sleep(1000); c('メモ→少し待って保存', ev('e1').memo === '持ち物');
  w.efAllDay(); c('終日→保存（時刻は消える）', ev('e1').allDay && !ev('e1').time);
  c('保存しても見えない入力画面は閉じている', !$('#eventModal').classList.contains('open') && !!$('#efPg'));
  w.epDup(); await sleep(5);
  c('別の日にも入れる→足す画面（日付欄が開いている）', w._ef.mode === 'add' && w._ef.o.title === 'CT 鈴木 健太さん' && w._ef.o.place === '会議室' && !!$('.efdi input[type=date]'));
  w.efDate('2026-10-27'); w.efSave(); await sleep(5);
  c('複製を保存', !!w.state.events.find(e => e.date === '2026-10-27' && e.title === 'CT 鈴木 健太さん'));
  w.openEventActions('e2'); w.epDel(); await sleep(5);
  c('消す', !ev('e2') && !$('#efPg'));
  w.openEventActions('t1'); c('タスクはタスクの画面（v616）', !!$('#tkPg') && !$('#efPg')); w.tkClose();
  console.log('=== ④ その他の入口・PC ===');
  w.evAddFor('a1'); c('その人の画面から：だれとが入る（メンバーだけ）', w._ef.o.mids.join() === 'a1' && w._ef.o.vis === 'member'); w.efClose();
  w.openEventAddTime('2026-10-21', 10); c('日表示の時間タップ：時刻入り', w._ef.o.time === '10:00' && w._ef.o.end === '11:00'); w.efClose();
  w.p2AddKindEv('CT'); c('PLANの＋予定：名前に種類', w._ef.o.title === 'CT '); w.efClose();
  setWH(1400, 900); w._uxSync(); w.setEventsMode('calendar'); await sleep(20);
  w.openEventAddDate('2026-10-21'); c('PCは今までの入力画面', $('#eventModal').classList.contains('open') && !$('#efPg')); w.closeEventModal(true);
});
