// v696：10人以上はサークルMAP／人を押して課題／課題→行動（分野を選ぶ）／シート型もフルネーム
const T = require('../lib/head.js')();
const { w, c, sleep, setWH, $, $$ } = T;
T.run(async () => {
  T.login(); setWH(390, 844); w.state.goals && (w._p2().sheet = w._p2().sheet || {}); w._p2Sh().mapViewM = 'sheet'; // v775: スマホの既定はツリー（ここではシート型を試す）
  w.switchView('plan'); await sleep(40);
  const mk = (n) => { const ms = [{ id: 'r', lastName: '山内', firstName: '北斗', title: 'ゴールド', parentId: '' }]; for (let i = 0; i < n; i++) ms.push({ id: 'm' + i, lastName: '佐藤' + i, firstName: '花', title: 'B1', parentId: i < 3 ? 'r' : 'm' + (i % 3), activity: 'S' }); return ms; };
  w.state.members = mk(5); w.state.idealMembers = [];
  w.p2Go('sheet'); await sleep(30);
  c('9人以下はシート型', $('#p2ShMF').dataset.kind === 'sheet' && !!$('.sp-map svg g.shn'));
  c('シート型もフルネーム（姓・名の2段）', /山内/.test($('.sp-map svg').innerHTML) && /北斗/.test($('.sp-map svg').innerHTML));
  w.p2ShIssTap('m1'); await sleep(40);
  c('人を押すと課題を書く欄', !!$('#p2ShIssIn') && /佐藤1/.test($('.iss').textContent));
  $('#p2ShIssIn').value = '審査フォロー'; $('#p2ShIssIn').onchange(); w.p2ShIssDone(); await sleep(20);
  const ym = w._p2Ym(0);
  c('課題を保存・一覧に出る', w._p2ShIss(ym).m1 === '審査フォロー' && /審査フォロー/.test($('.iss').textContent));
  c('課題のある人はMAPに印', /#FFB454/.test($('.sp-map svg').innerHTML));
  w.p2ShIssAct('m1'); await sleep(10);
  c('残す先→4分野＋タスク＋予定＋メモから選ぶ（v698）', $$('.iss-r .cats span').length === 7);
  const n0 = w.state.events.length; w.p2ShIssToAct('m1', 'dline'); await sleep(20);
  const e = w.state.events[w.state.events.length - 1];
  c('選んだ分野に行動が入る（名前つき）', w.state.events.length === n0 + 1 && e.planCat === 'dline' && /佐藤1さん：審査フォロー/.test(e.title));
  c('v698: 行動に入れたら連動の印', /Dライン/.test($('.iss-r .lk').textContent));
  w.p2ShIssTo('m1', 'memo'); await sleep(20);
  const mem = () => w.state.members.find(m => m.id === 'm1');
  c('v698: メモ＝メンバーのメモに入る', /【\d+年\d+月の課題】審査フォロー/.test(mem().memo || '') && /メモ/.test($('.iss-r .lk').textContent));
  w.p2ShIssTo('m1', 'task'); await sleep(60);
  c('v698: タスク＝その人つきの入力の画面（課題の文入り）', /佐藤1さん：審査フォロー/.test(($('#evTitle') || {}).value || ''));
  const t2 = w._tdMakeTask('佐藤1さん：審査フォロー', '', ''); t2.memberId = 'm1'; t2.createdAt = new w.Date(w.Date.now() + 1000).toISOString(); w.state.events.push(t2);
  await sleep(700);
  c('v698: 保存されたらタスクと連動', w._p2ShM(ym).issL.m1.task === t2.id);
  try { w.closeEventModal && w.closeEventModal(true); } catch (e) {}
  w.p2ShIssSave('m1', '審査フォロー2'); await sleep(10);
  c('v698: 課題を書き直すと残した先も直る（行動・タスク・メモ）', /審査フォロー2/.test(w.findEvent(w._p2ShM(ym).issL.m1.act).title) && /審査フォロー2/.test(t2.title) && /審査フォロー2/.test(mem().memo));
  c('v698: 課題のメモ（計画シート）は残る', w._p2ShIss(ym).m1 === '審査フォロー2');
  w.renderPlan(); await sleep(10);
  w.p2ShActTgl('front'); await sleep(10);
  c('v698: スマホの行動は分野ごとにたためる', !!$('.sp-at.cl') && /▶/.test($('.sp-at.cl .h').textContent));
  w.p2ShActTgl('front'); await sleep(10);
  c('v700: 拡大は全画面でなく枠の中（＋−・高さを変える帯・上に固定）', !$('#p2ShZoomOv') && !!$('#p2ShMF #p2ShMI svg') && !!$('.sp-zc') && !!$('.sp-mh') && !!$('.sp-pn'));
  w.p2ShZoom(1); c('v700: ＋で倍率が上がる', w._p2ShZ === 1.5 && $('#p2ShZL').textContent === '150%');
  w.p2ShIssTap('m2'); await sleep(60);
  c('v700: 拡大したまま人を押して課題を書ける（倍率は保つ）', !!$('#p2ShIssIn') && w._p2ShZ === 1.5 && $('#p2ShZL').textContent === '150%');
  w.p2ShIssDone(); w.p2ShZoom(0); c('v700: 全体に戻す', w._p2ShZ === 1);
  w.p2ShIssTgl(); await sleep(30);
  c('v700: 課題をたためる', !$('.iss-r') && /ひらく/.test($('.sp-mis').textContent) && w.localStorage.getItem('gm_shIssC') === '1');
  w.p2ShIssTap('m1'); await sleep(40);
  c('v700: たたんでいても人を押すと課題がひらく', !!$('#p2ShIssIn') && !w.localStorage.getItem('gm_shIssC'));
  w.p2ShIssDone(); await sleep(10);
  w.p2ShPinTgl(); await sleep(20);
  c('v700: 📌で上に固定（スマホは最初はしない）', !!$('.sp-mpin.on') && /固定中/.test($('.sp-pn').textContent));
  w.p2ShPinTgl(); await sleep(20);
  w.state.members = mk(12); setWH(1440, 1000); w._uxSync && w._uxSync(); w.renderPlan(); await sleep(40); // v775: 自動でサークル／シート型を選ぶのはPC（スマホは最初ツリー）
  c('10人以上はサークルMAP（自動）', $('#p2ShMF').dataset.kind === 'circle' && !!$('#p2ShMI svg'));
  c('v708: 計画シートのサークルはMAPの画面と別のid（MAPの＋−が効く）', $('#p2ShMI svg').id !== 'orbitSvgI' && $('#p2ShMI svg').id !== 'orbitSvgC');
  w.p2ShMapView('sheet'); await sleep(20);
  c('シート型に切りかえられる', $('#p2ShMF').dataset.kind === 'sheet' && !!$('.sp-map svg'));
  w.p2ShMapView(''); await sleep(20);
  c('自動に戻す', $('#p2ShMF').dataset.kind === 'circle');
  c('行動の4分野の欄はそのまま', $$('.sp-at').length === 4);
});
