// v615：フロント追加（新しい追加画面）・タイトルはカテゴリのカード→リスト・スタート月は年/月リスト
const T = require('../lib/head.js')();
const { w, c, sleep, setWH, $, $$ } = T;
T.run(async () => {
  T.login();
  const M = (id, p, title, x) => Object.assign({ id, lastName: id, firstName: '太郎', title, parentId: p, mapType: 'both', startMonth: '2020-01', ptSelf: 0 }, x || {});
  w.state.members = [M('r', '', 'BD', { activity: 'S', actRate: 100 }), M('g', 'r', 'BM', { lastName: '古藤', firstName: '雄貴', startMonth: '2021-05' })];
  w.state.idealMembers = []; w.state.events = [];
  try { w.recalcAllGSV(); } catch (e) {}
  setWH(390, 844); w.switchView('current'); await sleep(100);
  const G = () => w.state.members.find(m => m.id === 'g');
  console.log('=== ① その人の画面：右下は「フロント追加」 ===');
  w.ppOpen('g', 'current'); await sleep(10);
  c('右下「＋ フロント追加」', $('#ppPg .ux-nx').textContent.indexOf('フロント追加') >= 0);
  console.log('=== ② タイトル：カテゴリのカード→押すとリスト ===');
  w.ppGo('title'); await sleep(5);
  const cards = $$('#ppPg .ttc');
  c('最初はカードだけ（リストは閉じている）', cards.length === 5 && !$('#ppPg .ttc .ls'));
  c('カードに範囲（FT〜CO・LOI〜Q4・B1〜BM・BR〜TE）', ['FT〜CO', 'LOI〜Q4', 'B1〜BM', 'BR〜TE'].every(x => $('#ppPg').textContent.indexOf(x) >= 0));
  c('今のタイトル（BM）がBAのカードに', cards[2].querySelector('.cur') && cards[2].querySelector('.cur').textContent === 'BM');
  w.ttlTgl('BR', '_ppRender'); await sleep(5);
  c('押すとそのカテゴリだけリストで開く', $$('#ppPg .ttc .ls').length === 1 && $$('#ppPg .ttc.on .rw').length === 9 && $('#ppPg .ttc.on').textContent.indexOf('ゴールド') >= 0);
  w.ttlTgl('BR', '_ppRender'); c('もう一度押すと閉じる', !$('#ppPg .ttc .ls'));
  w.ttlTgl('BR', '_ppRender'); w.ppTitle('ゴールド'); await sleep(10);
  c('選ぶとすぐ保存・カードは閉じる', G().title === 'ゴールド' && !$('#ppPg .ttc .ls') && $$('#ppPg .ttc')[3].querySelector('.cur').textContent === (w.titleAbbr('ゴールド') || 'ゴールド'));
  console.log('=== ③ スタート月：年と月のリスト ===');
  w.ppGo('prof'); await sleep(5);
  c('年と月のリスト（今の値）', $('#ymY').value === '2021' && $('#ymM').value === '5');
  c('年は1990年まで選べる', !!$('#ymY option[value="1990"]'));
  $('#ymY').value = '2019'; w.ppStartYM(); await sleep(5);
  c('年を変える→保存', String(G().startMonth).replace('.', '-') === '2019-05', G().startMonth);
  $('#ymM').value = '11'; w.ppStartYM(); await sleep(5);
  c('月を変える→保存', String(G().startMonth).replace('.', '-') === '2019-11', G().startMonth);
  w.ppClose();
  console.log('=== ④ フロント追加 ===');
  w.ppOpen('g', 'current'); w.naOpen('g'); await sleep(10);
  c('追加画面（その人の下に）', !!$('#naPg') && $('#naPg h2').textContent.indexOf('古藤 雄貴さんの下に追加') >= 0);
  c('名前・性別・タイトル（カード）', !!$('#naLast') && !!$('#naFirst') && $$('#naPg .ppb span').length >= 2 && $$('#naPg .ttc').length === 4);
  c('既定はマケ（研修生）→研修の予定欄', $$('#naPg .ttc')[0].querySelector('.cur').textContent === 'マケ' && !!$('#naDate') && !$('#naGsv'));
  w.naSave(''); c('名前がないと追加しない', !!$('#naPg'));
  $('#naLast').value = '佐藤'; $('#naFirst').value = '花'; $('#naDate').value = '2026-10-20'; $('#naAsan').value = '山内';
  w.naSet('gender', 'female');
  c('描き直しても入力は残る', $('#naLast').value === '佐藤' && $('#naDate').value === '2026-10-20');
  const n0 = w.state.members.length; w.naSave(''); await sleep(10);
  const s = w.state.members.find(m => m.lastName === '佐藤');
  c('追加（直下・女性・マケ・研修の予定）', w.state.members.length === n0 + 1 && s.parentId === 'g' && s.gender === 'female' && s.title === 'マケ' && s.traineeHistory.length === 1 && s.traineeHistory[0].date === '2026-10-20' && s.aSan === '山内');
  c('閉じると元の人の画面', !$('#naPg') && !!$('#ppPg'));
  w.naOpen('g'); w.ttlTgl('BA', '_naRender'); w.naTitle('B1'); await sleep(5);
  c('BAを選ぶと稼働・GSV欄', !!$('#naGsv') && !$('#naDate') && $$('#naPg .ttc')[2].querySelector('.cur').textContent === 'B1');
  $('#naLast').value = '田中'; w.naSet('act', 'B'); $('#naGsv').value = '300'; w.naSave('cont'); await sleep(5);
  const t = w.state.members.find(m => m.lastName === '田中');
  c('続けて入れる（画面は残り名前は空）', t && t.title === 'B1' && t.activity === 'B' && t.ptCurrent === 300 && !!$('#naPg') && $('#naLast').value === '');
  w.naChg(); c('追加先を変えられる', !!$('#naPg .nap select'));
  w.naSet('pid', 'r'); $('#naLast').value = '鈴木'; w.naSave('more'); await sleep(10);
  const u = w.state.members.find(m => m.lastName === '鈴木');
  c('くわしく入れる→その人の画面', u && u.parentId === 'r' && !$('#naPg') && w._pp && w._pp.id === u.id);
  w.ppClose();
  console.log('=== ⑤ MAPの＋追加・PC ===');
  w._selectedCardId = null; w.onFabClick(); c('MAPの＋追加も新しい画面', !!$('#naPg')); w.naClose();
  setWH(1400, 900); w._uxSync(); await sleep(10);
  w.selectedParentId = 'g'; w.openQuickAdd(); c('PCは今までのかんたん追加', !!w.document.getElementById('qaOv') && !$('#naPg'));
});
