// v617：OL（スマホ）＝入口・企画1枚・その人のOL・反応を記入
const T = require('../lib/head.js')();
const { w, c, sleep, setWH, $, $$ } = T;
T.run(async () => {
  T.login();
  const F = (id, ln, fn, t) => ({ id, lastName: ln, firstName: fn, title: t, parentId: 'r', mapType: 'both' });
  w.state.members = [{ id: 'r', lastName: '山内', firstName: '北斗', title: 'ゴールド', parentId: '', mapType: 'both' }, F('f1', '佐藤', '花', 'B1'), F('f2', '田中', '健', 'Q2'), F('f3', '鈴木', '一郎', 'B3'), F('f4', '高橋', '翔', 'LOI'), F('f5', '伊藤', '真', 'B5')];
  w.state.events = [];
  w.state.freshData = {};
  const L = (mid, r) => { const f = w.state.freshData[mid] = w.state.freshData[mid] || {}; f.olLog = (f.olLog || []).concat([r]); };
  ['f1', 'f2', 'f3'].forEach(m => L(m, { date: '2026-10-03', time: '20:00', asan: '山内', what: 'ビジョン共有', note: '前向き', st: 'done', gid: 'g1', mids: ['f1', 'f2', 'f3'], kind: 'group' }));
  L('f5', { date: '2026-09-01', asan: '山内', what: '近況', note: '忙しそう', st: 'done', gid: 'g3', mids: ['f5'], kind: 'solo' });
  L('f2', { date: '2026-10-10', time: '21:00', asan: '山内', st: 'planned', gid: 'g4', mids: ['f2'], kind: 'solo' });
  w.state.currentMonth = '2026.10';
  setWH(390, 844);
  w.switchView('ol'); await sleep(50);
  console.log('=== ① 入口 ===');
  c('新しい入口（古い上の帯は隠れる）', !!$('.olh') && w.document.body.classList.contains('olh-on'));
  const kp = $$('.olh-kp>div');
  c('大きい数字：3〜7人OL 1/3・個別0・要フォロー', kp.length === 3 && kp[0].textContent.indexOf('1') >= 0 && kp[0].textContent.indexOf('/3回') >= 0 && kp[1].textContent.indexOf('0') >= 0);
  c('3〜7人OLの枠①②③（空き枠は企画）', $$('.olh-sl.done').length === 1 && $$('.olh-sl.empty').length === 2);
  c('日付が過ぎた予定は「反応を記入」', $('.olh').textContent.indexOf('反応を記入') >= 0 && !!$('.olh-sl.over'));
  c('「できなかった」は出さない', $('.olh').textContent.indexOf('できなかった') < 0);
  const fr = $$('.olh-fr');
  c('フレッシュ要フォロー順（未接触の高橋が先・伊藤43日）', fr[0].textContent.indexOf('高橋') >= 0 && $('.olh').textContent.indexOf('43') >= 0);
  w.olNeed(); c('要フォローのカードで絞り込み', $$('.olh-fr').every(x => !x.classList.contains('ok')) && $$('.olh-kp>div')[2].classList.contains('on')); w.olNeed();
  c('下の帯：‹戻る・＋OLを企画', $('.olh ~ .ux-btm, #olTabWrap .ux-btm').textContent.indexOf('OLを企画') >= 0);
  console.log('=== ② 反応を記入 ===');
  w.olEventOpen('g4', { result: true }); await sleep(150);
  c('反応を記入のページ（どうだった？は聞かない）', !!$('#olpPg') && $('#olpPg').textContent.indexOf('反応を記入') >= 0 && $('#olpPg').textContent.indexOf('どうだった') < 0 && $('#olpPg').textContent.indexOf('田中 健') >= 0);
  $('#olpNote').value = 'PGに来たいと言っていた'; w.olpField('note', 'PGに来たいと言っていた');
  w.olpSave(); await sleep(30);
  const r4 = w.state.freshData.f2.olLog.find(r => r.gid === 'g4');
  c('保存＝実施済み＋反応', r4.st === 'done' && r4.note === 'PGに来たいと言っていた' && !$('#olpPg'));
  c('入口から「反応を記入」が消える', !$('.olh-sl.over'));
  console.log('=== ③ その人のOL ===');
  w.olFreshTap('f5'); await sleep(5);
  c('その人のOL（日数・記録）', !!$('#olmPg') && $('#olmPg .big').textContent.indexOf('43') >= 0 && $$('#olmPg .olm-ti').length === 1 && $('#olmPg').textContent.indexOf('忙しそう') >= 0);
  console.log('=== ④ OLを企画（1枚） ===');
  w.olPlanStart({ mids: ['f5'] }); await sleep(5);
  c('1枚の企画ページ（個別OLが既定・伊藤が入っている）', !!$('#olpPg') && w._olp.kind === 'solo' && $('#olpPg .efsel').textContent.indexOf('伊藤 真') >= 0 && $$('#olpPg .olpk span.on').length === 1);
  c('だれと：要フォロー順のリスト（日数つき）', $$('#olpWhoLs .efr').length >= 4 && $('#olpWhoLs').textContent.indexOf('未接触') >= 0);
  w.olpSetKind('group'); w.olpToggle('f4'); w.olpToggle('f1');
  c('3〜7人OLで3人', w._olp.kind === 'group' && w._olp.mids.length === 3 && $('#olpPg').textContent.indexOf('3人 ✓') >= 0);
  w.olpOpenDate(); $('#olpDate').value = '2026-10-24'; w.olpField('date', '2026-10-24'); w._olpRender();
  w.openTimePad('olT'); w.tpKey('2'); w.tpKey('0'); w.tpKey('00'); await sleep(450);
  c('時刻は今の数字パッド', w._olp.time === '20:00' && $('#olT').value === '20:00');
  w.olpChip('asan', '山内'); w.olpField('what', '目標設定');
  w.olpSave(); await sleep(30);
  const g = w.state.freshData.f4.olLog.find(r => r.date === '2026-10-24');
  c('予定に入れる（全員に記録・予定にも）', g && g.kind === 'group' && g.st === 'planned' && g.time === '20:00' && g.mids.length === 3 && w.state.events.some(e => e.olGid === g.gid && e.date === '2026-10-24'));
  c('閉じると入口・その人のページが更新', !$('#olpPg') && $$('.olh-sl.plan').length === 1);
  w.olmClose();
  console.log('=== ⑤ PC ===');
  setWH(1400, 900); w._uxSync(); w.renderOlTab(); await sleep(10);
  c('PCは今までのOL', !$('.olh') && !w.document.body.classList.contains('olh-on'));
  w.switchView('home'); c('ほかの画面へ行くと帯が戻る', !w.document.body.classList.contains('olh-on'));
});
