// v624：PLAN・データ（PC）＝左に入口のタイル／右に選んだページ
const T = require('../lib/head.js')();
const { w, c, sleep, setWH, $, $$ } = T;
T.run(async () => {
  T.login();
  w.state.members = [{ id: 'r', lastName: '山内', firstName: '北斗', title: 'ゴールド', parentId: '', mapType: 'both', activity: 'S', actRate: 100 }, { id: 'a', lastName: '佐藤', firstName: '花', title: 'B1', parentId: 'r', mapType: 'both', activity: 'S' }];
  w.state.currentMonth = '2026.10';
  setWH(1400, 900); w._uxSync();
  console.log('=== ① PLAN（v630：上にタブ） ===');
  w.switchView('plan'); await sleep(50);
  c('上にタブ（サマリー・理想・目標・ロードマップ・今月の目標・今週やること・振り返り・ツール）', !!$('.pcx2-tabs') && $$('.pcx2-tabs span').length === 8 && !$('.pcx-n'));
  c('最初はサマリー', w._p2Pg === 'sum' && $('.pcx2-tabs span.on').textContent.indexOf('サマリー') >= 0 && !!$('.p2s'));
  c('スマホ用の下の帯・上の帯の形は使わない', !w.document.body.classList.contains('ux-pg') && !w.document.body.classList.contains('ux-hub'));
  w.state.goals.plan.income = 3410000; w.state.goals.plan.title = 'チームエリート'; w.state.goals.plan.deadline = '2027-12'; w._p2().motto = 'やる時はいましかない';
  w.p2Go('sum'); await sleep(20);
  const sum = $('.p2s').textContent;
  c('サマリー：目標・次の山・マイルストーン・年ごとの目標・理想の生活・やりたいこと・今月の目標・今週やること', ['341', 'TEAM ELITE', 'やる時はいましかない', '次の山', 'マイルストーン', '年ごとの目標', '理想の生活', 'やりたいこと', '月の目標と今', '今週やること'].every(t => sum.indexOf(t) >= 0));
  c('サマリーに想い（作文）は出さない', sum.indexOf('やる理由') < 0);
  w.p2Go('mon'); await sleep(20);
  c('10月の目標：表で入れる（入力欄・＋−なし）', !!$('.pcx-tb2') && $$('.pcx-tb2 .pcx-in').length >= 8 && $('.pcx-p').textContent.indexOf('今月（10月）') >= 0);
  const sIn = $$('.pcx-tb2 .pcx-in')[0]; sIn.value = '6'; sIn.onchange(); await sleep(10);
  c('入れたらその場で保存', String(w._p2M(w._p2Ym(0)).s) === '6');
  w.p2MonFor(1); await sleep(20);
  c('来月に切り替え', $('.pcx-p h2').textContent.indexOf('11月') >= 0); w.p2MonFor(0);
  w.p2Go('goal'); await sleep(20);
  c('目標：ポップアップをやめて画面に直接（①最終ゴール②1年ごと③次の山）', !!$('#p2GeInline #p2geInc') && !$('#p2GeOv') && $('#p2GeInline').textContent.indexOf('① 最終ゴール') >= 0 && $('#p2GeInline').textContent.indexOf('③ 次の山') >= 0);
  w.p2GoalEdit(); await sleep(20);
  c('「目標をなおす」もPCでは目標のページへ', w._p2Pg === 'goal' && !$('#p2GeOv'));
  c('スローガンも目標のページで', !!$('.pcx-gl input.pcx-in'));
  w.p2Go('ideal'); await sleep(20);
  c('理想：項目のタブ（7）＋次へ', $$('.pcx-tabs span').length === 7 && !!$('.pcx-h .pcx-b.p'));
  w.p2Go('gap'); await sleep(20);
  c('ツールの先のページでも「ツール」のタブ・戻るあり', $('.pcx2-tabs span.on').textContent.indexOf('ツール') >= 0 && $('.pcx-h').textContent.indexOf('戻る') >= 0);
  w.p2Go('do'); await sleep(20);
  c('今週やること：今までのPCの一覧', $('.pcx-p').textContent.indexOf('今週やること') >= 0);
  console.log('=== ② データ ===');
  w._dtMode = 'ez'; w.switchView('stats'); await sleep(50);
  c('左に入口のタイル＋くわしくの表のボタン', !!$('#dtPcNav') && $('#view-stats').classList.contains('pcx-st') && $$('#dtPcNav .pcx-t').length === 5 && $$('#dtPcNav .pcx-sm span').length === 5);
  c('右にグラフと数字のページ', $('#dtEz').classList.contains('pcx-dp') && !!$('#dtEz .dtu-pg') && !!$('#dtEz .pcx-tb'));
  w.dtPcGo('s'); await sleep(20);
  c('S稼働へ切り替え', $('#dtEz h2').textContent === 'S稼働' && $$('#dtPcNav .pcx-t.on').length === 1);
  w.dtMode('full', 'trend'); await sleep(30);
  c('推移（くわしく）も左の列はそのまま', !!$('#dtPcNav') && $('#dtPcNav .pcx-sm span.on').textContent.indexOf('推移') >= 0 && $('#dtEz').style.display === 'none');
  w.dtGo('exam'); await sleep(20);
  c('ページの中のリンク（dtGo）もPCの右の欄へ', w._dtMode === 'ez' && $('#dtEz h2').textContent === 'BR');
  console.log('=== ③ スマホは今まで通り ===');
  setWH(390, 844); w._uxSync(); w.switchView('menu'); await sleep(30);
  const tl = $$('#view-menu .ux-t b').map(x => x.textContent);
  c('v631: メニューのタイルは PLAN・MAP・カレンダー・TODO・分析', JSON.stringify(tl) === JSON.stringify(['PLAN', 'MAP', 'カレンダー', 'TODO', '分析']), JSON.stringify(tl));
  c('理想MAP・OL・再アプローチは下のボタンに', ['理想MAP', 'OL', '再アプローチ'].every(t => $('#view-menu .ux-sm').textContent.indexOf(t) >= 0));
  $$('#view-menu .ux-t')[4].click(); await sleep(30);
  c('分析＝データタブ', w.currentView === 'stats');
  setWH(390, 844); w._uxSync(); w.switchView('plan'); await sleep(30);
  c('PLAN：スマホは入口のタイル', !$('.pcx2') && !!$('#view-plan .ux-hub, #view-plan .ux-pg'));
  w.p2Go('sum'); await sleep(20);
  c('スマホもサマリー（入口の「サマリー」から）', !!$('#view-plan .p2s') && $('#view-plan').textContent.indexOf('サマリー') >= 0);
  w.switchView('stats'); await sleep(30);
  c('データ：PCの左の列は出ない', !$('#dtPcNav') && !$('#view-stats').classList.contains('pcx-st'));
  w.dtMode('full', 'trend'); await sleep(20);
  c('v626: スマホも「ざっくり／くわしく」は出ない（入口へ戻るだけ）', $('#dtModeBar').textContent.indexOf('ざっくり') < 0 && $('#dtModeBar').textContent.indexOf('入口') >= 0);
  w.dtMode('ez'); await sleep(20);
  c('入口では何も出さない', $('#dtModeBar').textContent === '');
});
