// v624：PLAN・データ（PC）＝左に入口のタイル／右に選んだページ
const T = require('../lib/head.js')();
const { w, c, sleep, setWH, $, $$ } = T;
T.run(async () => {
  T.login();
  w.state.members = [{ id: 'r', lastName: '山内', firstName: '北斗', title: 'ゴールド', parentId: '', mapType: 'both', activity: 'S', actRate: 100 }, { id: 'a', lastName: '佐藤', firstName: '花', title: 'B1', parentId: 'r', mapType: 'both', activity: 'S' }];
  w.state.currentMonth = '2026.10';
  setWH(1400, 900); w._uxSync();
  console.log('=== ① PLAN ===');
  w.switchView('plan'); await sleep(50);
  c('左に入口のタイル（5つ）＋振り返り・ツール', !!$('.pcx') && $$('.pcx-n .pcx-t').length === 5 && $('.pcx-n').textContent.indexOf('振り返り') >= 0);
  c('最初から右にページ（選んだタイルが光る）', $$('.pcx-n .pcx-t.on').length === 1 && !!$('.pcx-p .pcx-h'));
  c('スマホ用の下の帯・上の帯の形は使わない', !w.document.body.classList.contains('ux-pg') && !w.document.body.classList.contains('ux-hub'));
  w.p2Go('mon'); await sleep(20);
  const n = w._p2MonPages().length;
  c('10月の目標：1項目ずつ→全部をカードで1画面に', $$('.pcx-p .pcx-c').length === n && $('.pcx-p').textContent.indexOf('今月（10月）') >= 0);
  w.p2MonFor(1); await sleep(20);
  c('来月に切り替え', $('.pcx-p h2').textContent.indexOf('11月') >= 0); w.p2MonFor(0);
  w.p2Go('goal'); await sleep(20);
  c('目標：6つを1画面に', $$('.pcx-p .pcx-c').length === 6);
  w.p2Go('why'); await sleep(20);
  c('想い：項目のタブ（10）＋次へ', $$('.pcx-tabs span').length === 10 && !!$('.pcx-h .pcx-b.p'));
  w.p2PgSub(3); await sleep(20);
  c('タブで項目を切り替え', $$('.pcx-tabs span')[3].classList.contains('on'));
  w.p2Go('gap'); await sleep(20);
  c('ツールの先のページでも「ツール」が光る・戻るあり', $('.pcx-sm span.on') && $('.pcx-sm span.on').textContent.indexOf('ツール') >= 0 && $('.pcx-h').textContent.indexOf('戻る') >= 0);
  w.p2Go('do'); await sleep(20);
  c('今週やること：今までのPCの一覧', $('.pcx-p').textContent.indexOf('今週やること') >= 0 && $$('.pcx-n .pcx-t.on').length === 1);
  console.log('=== ② データ ===');
  w._dtMode = 'ez'; w.switchView('stats'); await sleep(50);
  c('左に入口のタイル＋くわしくの表のボタン', !!$('#dtPcNav') && $('#view-stats').classList.contains('pcx-st') && $$('#dtPcNav .pcx-t').length === 5 && $$('#dtPcNav .pcx-sm span').length === 5);
  c('右にグラフと数字のページ', $('#dtEz').classList.contains('pcx-dp') && !!$('#dtEz .dtu-pg') && !!$('#dtEz .pcx-tb'));
  w.dtPcGo('s'); await sleep(20);
  c('S稼働へ切り替え', $('#dtEz h2').textContent === 'S稼働' && $$('#dtPcNav .pcx-t.on').length === 1);
  w.dtMode('full', 'trend'); await sleep(30);
  c('推移（くわしく）も左の列はそのまま', !!$('#dtPcNav') && $('#dtPcNav .pcx-sm span.on').textContent.indexOf('推移') >= 0 && $('#dtEz').style.display === 'none');
  w.dtGo('exam'); await sleep(20);
  c('ページの中のリンク（dtGo）もPCの右の欄へ', w._dtMode === 'ez' && $('#dtEz h2').textContent === 'BR');
  console.log('=== ③ スマホは今まで通り ===');
  setWH(390, 844); w._uxSync(); w.switchView('plan'); await sleep(30);
  c('PLAN：スマホは入口のタイル', !$('.pcx') && !!$('#view-plan .ux-hub, #view-plan .ux-pg'));
  w.switchView('stats'); await sleep(30);
  c('データ：PCの左の列は出ない', !$('#dtPcNav') && !$('#view-stats').classList.contains('pcx-st'));
});
