// v652：PLANの入口にシミュレーション・チェック・夢100／タイルを終えたら入口へ／シミュレーションの見直し／チェックのタブ・予定へ・ひとこと／BB早見表の表
const T = require('../lib/head.js')();
const { w, c, sleep, setWH, $, $$ } = T;
T.run(async () => {
  T.login();
  w.state.members = [{ id: 'r', lastName: '山内', firstName: '北斗', title: 'ゴールド', parentId: '', mapType: 'both', ptCurrent: 2500 }];
  setWH(390, 844); w._uxSync && w._uxSync(); w.switchView('plan'); await sleep(40);
  w.state.goals.plan.income = 3410000; w.state.goals.plan.title = 'チームエリート'; w.state.goals.plan.deadline = '2029-12';
  w.p2Go(''); await sleep(20);
  const lbs = $$('#view-plan .ux-t b').map(x => x.textContent);
  c('入口（v736）：年の目標・計画シート・やることの順、その下に理想・夢100・シミュレーション', lbs[0] === '年の目標・ロードマップ' && /月の計画シート/.test(lbs[1]) && lbs.slice(2, 6).join() === 'やること,理想,夢100,シミュレーション', lbs.join());
  c('v686: 今週やることのタイルはなし（計画シートの行動に）', lbs.indexOf('今週やること') < 0);
  w.p2Go('do'); await sleep(10);
  c('v653: 今週やることの上に◯月の目標（押すと目標のページ）', $('#view-plan .ux-li').textContent.indexOf('月の目標') >= 0 && $('#view-plan .ux-li').getAttribute('onclick') === "p2Go('mon')");
  w.p2Go('goal', 5); await sleep(10);
  c('タイルの最後は「✓ 完了」で入口へ（次のタイルへは行かない）', $('.ux-btm .ux-nx').textContent === '✓ 完了' && $('.ux-btm .ux-nx').getAttribute('onclick') === "p2Go('')");
  console.log('=== シミュレーション ===');
  delete w._p2().sim; w._p2SimMo = 3; w.p2Go(''); w.p2Go('sim'); await sleep(20);
  const tx = $('#view-plan').textContent;
  c('「これだけやったら…」はなし・凡例は「new」', tx.indexOf('これだけやったら、いくら狙えるか') < 0 && $('.p2sm-lg').textContent.indexOf('new') >= 0 && $('.p2sm-lg').textContent.indexOf('に入った人') < 0);
  c('ファーストボーナスは大きく（v694：一番上・内訳は(i)）', !!$('.sm1-r .fb') && $('.sm1-r .fb').textContent.indexOf('ビルディングボーナス') < 0);
  w.uxInfo('simfb'); c('(i)にBB・LOI特典の内訳', $('#uxInfo').textContent.indexOf('ビルディングボーナス') >= 0 && $('#uxInfo').textContent.indexOf('エリートLOI特典') >= 0 && $('#uxInfo .ok').textContent === 'とじる'); w.uxInfoClose();
  c('戻る＝入口（入口から開いた時）', $('.ux-btm .ux-bk').getAttribute('onclick') === "p2Go('')");
  w.p2SimDupSet(2); await sleep(5);
  c('数字を変えたら組織図はLOIの月に', w._p2SimMo === 0 && $('.p2sm-seg span.on').textContent.indexOf('LOI') >= 0);
  c('設定はマスに書くだけ（v694：＋−なし）', !!$('.sm1-g .sp-in') && !$('#view-plan .ux-stp'));
  console.log('=== チェック ===');
  w.p2Go(''); w.p2Go('ck'); await sleep(10);
  c('必須アイテム／TRAINING はタブ', $$('.p2ck-tabs span').length === 2 && $$('.p2ck-r').length === w.P2_CK_ESS.length);
  w.p2CkTab('tr'); await sleep(5); c('TRAININGタブ', $$('.p2ck-r').length === w.P2_CK_TR.length);
  c('v746: 日付は最初「未設定」（勝手に入らない）', /未設定/.test($$('.p2ck-r .dtc')[0].textContent) && !$('.p2ck-r input[type=date]'));
  const n0 = w.state.events.length; w.p2CkDt('tr', 0); await sleep(10);
  c('v746: 押すと計画シートと同じ窓（ToDo／予定・日付は空）', !!$('#p2ShDtOv') && /ToDoに入れる/.test($('#p2ShDtOv').textContent) && $('#p2ShDtD').value === '');
  $('#p2ShDtD').value = '2026-11-03'; w.p2ShDtOk(); await sleep(20);
  const ck0 = w.state.events[w.state.events.length - 1];
  c('v746: ToDoに入る（日付つき）・欄に「11/3 ToDo」', w.state.events.length === n0 + 1 && ck0.type === 'task' && ck0.date === '2026-11-03' && /11\/3/.test($$('.p2ck-r .dtc')[0].textContent) && /ToDo/.test($$('.p2ck-r .dtc')[0].textContent));
  w.toggleEventDone(ck0.id); w.renderPlan(); await sleep(10);
  c('v746: ToDoでチェックするとチェックリストもチェック', $$('.p2ck-r')[0].classList.contains('done'));
  w.p2CkDt('tr', 0); await sleep(10); w.p2ShDtKind('ev'); await sleep(10);
  w.openTimePad('p2ShDtT'); await sleep(5); w.tpKey('1'); w.tpKey('9'); w.tpKey('00'); w.closeTimePad(true); await sleep(10);
  w.p2ShDtOk(); await sleep(20);
  c('v746: 予定に切りかえ（同じ予定を直す・19:00〜20:00）', w.state.events.length === n0 + 1 && ck0.type === 'event' && ck0.time === '19:00' && ck0.endTime === '20:00' && /予定 19:00/.test($$('.p2ck-r .dtc')[0].textContent));
  w.p2CkDt('tr', 0); await sleep(10); w.p2ShDtClear(); await sleep(20);
  c('v746: 期日を消すと未設定に戻り、入れた予定も消える', /未設定/.test($$('.p2ck-r .dtc')[0].textContent) && !w.state.events.some(e => e.id === ck0.id && !e.deleted));
  w.p2CkTgl('tr', 1); await sleep(10);
  c('チェックすると色つきのひとこと', !!$('#p2Cheer') && $('#p2Cheer').classList.contains('on') && w.P2_CHEER.some(x => $('#p2Cheer').textContent.indexOf(x[0]) === 0 || $('#p2Cheer').textContent.indexOf('準備万端') >= 0));
  console.log('=== BB早見表 ===');
  w.p2Go('bb'); await sleep(10);
  c('早見表（GSV・ブロック・BB）', $$('.p2bb-t > div').length === w.P2_BB_TABLE.length + 1 && !!$('.p2bb-t .on'));
});
