// v686：PLANの中心を「計画シート」に（年の目標・月間目標・MAP・数字・改善点・4分野の行動＝ToDo）
const T = require('../lib/head.js')();
const { w, c, sleep, setWH, $, $$ } = T;
T.run(async () => {
  T.login(); setWH(390, 844);
  w.switchView('plan'); await sleep(50);
  const s = w.state, ym = w._p2Ym(0);
  s.members = [{ id: 'r', lastName: '山内', title: 'ゴールド', parentId: '', ptCurrent: 3200, activity: 'S' },
    { id: 'a', lastName: '佐藤', title: 'BR', parentId: 'r', ptCurrent: 2000, activity: 'S', startMonth: '2025-01' },
    { id: 'u', lastName: '林', title: 'ユーザー', parentId: 'r', ptCurrent: 300, activity: 'B', startMonth: '2025-01' },
    { id: 'n', lastName: '井上', title: 'LOI', parentId: 'r', ptCurrent: 1100, startMonth: ym }];
  s.idealMembers = [];
  const p = s.goals.plan; p.income = 3410000; p.title = 'チームエリート'; p.deadline = '2027-12';
  w.currentUser.union = 'GRANT';
  w.p2Go(''); await sleep(20);
  const t0 = $('#view-plan .ux-t');
  c('入口の一番上は今月の計画シート', /月の計画シート/.test(t0.textContent));
  c('入口に「年の目標・ロードマップ」・理想・夢100・シミュレーション', ['年の目標・ロードマップ', '理想', '夢100', 'シミュレーション'].every(x => $('#view-plan').textContent.indexOf(x) >= 0));
  c('入口にシートを印刷・ツール', /シートを印刷/.test($('#view-plan .ux-foot').textContent) && /ツール/.test($('#view-plan .ux-foot').textContent));
  w.p2Go('tool'); await sleep(10);
  c('前の画面（目標・今週やること・振り返り・サマリー）はツールに', ['目標', '今週やること', '振り返り', 'サマリー'].every(x => $('#view-plan').textContent.indexOf(x) >= 0));
  w.p2Go('sheet', 0); await sleep(20);
  const v = $('#view-plan').textContent;
  c('1. 目標・MAP：年の目標・月間目標・MAP・ユニオン名', /年の目標/.test(v) && /341/.test(v) && /TEAM ELITE/.test(v) && /月間目標/.test(v) && /【GRANT】/.test(v) && !!$('#view-plan .sh-map svg'));
  c('MAP：上が流通・下がビジネス（ユーザーは上）', (() => { const sv = $('#view-plan .sh-map svg').innerHTML; return /流通/.test(sv) && /ビジネス/.test(sv); })());
  const map = w._p2ShMapSvg({ W: 640, H: 430, mode: 'cur', newN: 0 });
  c('MAPに自分と3人', map.n === 4);
  w.p2ShIncStep(1); await sleep(10);
  c('月収の目標を＋（5万ずつ）', w._p2M(ym).comm === 5);
  w.p2ShFrStep(1); w.p2ShFrStep(1); await sleep(10);
  c('NEWフロントの目標（ロードマップ・月の目標と同じ数字）', +w._p2FrontTgt(ym) === 2);
  c('NEWフロントの今＝今月足した直下（井上）', w._p2ShFr(ym).now === 1);
  w.p2ShMap('cur'); await sleep(10);
  c('現状のMAPに点線のNEW（目標2−今1）', /NEW/.test($('#view-plan .sh-map svg').innerHTML));
  w.p2PgSub(1); await sleep(20);
  c('2. 数字：8項目', $$('#view-plan .sh-k').length === 8);
  c('フロント（B1）は自動・目標はNEWフロントと同じ', /自動/.test($$('#view-plan .sh-k')[0].textContent) && w._p2ShKv(ym, w._p2ShK('front')).t === 2 && w._p2ShKv(ym, w._p2ShK('front')).v === 1);
  w.p2ShKT('ids', 1); w.p2ShKT('ids', 1); w.p2ShKV('ids', 1); await sleep(10);
  c('入力の項目：目標と今を＋−', w._p2ShKv(ym, w._p2ShK('ids')).t === 2 && w._p2ShKv(ym, w._p2ShK('ids')).v === 1);
  w.p2ShKEd(); await sleep(10);
  c('項目を変える：名前・数え方', $$('#view-plan .sh-ke .row').length === 8 && !!$('#view-plan .sh-ke select'));
  w.p2ShKAdd(); w.p2ShKRen(8, '紹介数'); await sleep(10);
  c('項目を足せる', w._p2Sh().kpi.length === 9 && w._p2Sh().kpi[8].lb === '紹介数');
  w.p2ShKDel(8); w.p2ShKAuto(5, 'ct'); await sleep(10);
  c('数え方を自動（予定：CT）に変えられる', w._p2Sh().kpi[5].a === 'ct');
  w.p2ShKAuto(5, ''); w.p2ShKEd();
  w.p2PgSub(2); await sleep(20);
  c('3. 行動：4分野', $$('#view-plan .sh-cats span').length === 4 && /フロント作り/.test($('#view-plan .sh-cats').textContent));
  const n0 = s.events.length;
  $('#p2ShIn_front').value = '伊藤さんとFT'; $('#p2ShDt_front').value = ym + '-15'; w.p2ShActAdd('front'); await sleep(40);
  const e = s.events[s.events.length - 1];
  c('行動を足す＝ToDoのタスク（期日つき）', s.events.length === n0 + 1 && e.type === 'task' && e.title === '伊藤さんとFT' && e.date === ym + '-15' && e.planCat === 'front' && e.planYm === ym);
  c('リストに出る', /伊藤さんとFT/.test($('#view-plan .sh-al').textContent));
  w.p2ShActTg(e.id); await sleep(20);
  c('チェック＝ToDoの完了', e.done === true && !!$('#view-plan .sh-al .it.dn'));
  w.p2ShCat('self'); await sleep(10);
  c('分野を切りかえ', /自己成長/.test($('#view-plan .sh-al').textContent));
  w.p2PgSub(3); await sleep(20);
  w._p2ShM(w._p2YmAdd(ym, -1)).kaizen = 'CT取りの時間を固定'; w.p2PgSub(3); await sleep(10);
  c('4. 改善点：先月の改善点を見ながら書く', /CT取りの時間を固定/.test($('#view-plan .sh-kz').textContent) && !!$('#view-plan .sh-kz textarea'));
  w.p2ShKz('前日に確認の連絡'); c('改善点を保存', w._p2ShM(ym).kaizen === '前日に確認の連絡');
  c('最後は「✓ 完了」', /完了/.test($('.ux-btm .ux-nx').textContent));
  const ph = w._p2ShPrintHtml(ym);
  c('印刷：A3横・紙と同じ項目', /size:A3 landscape/.test(ph) && /計画立案シート/.test(ph) && /＜MAP＞/.test(ph) && /＜改善点＞/.test(ph) && /実行期日/.test(ph) && /伊藤さんとFT/.test(ph) && /【GRANT】/.test(ph));
  w.p2ShMon(-1); await sleep(10);
  c('先月のシートに切りかえ', w._p2ShYmN() === w._p2YmAdd(ym, -1)); w.p2ShMon(1);
  setWH(1400, 900); w._uxSync(); w.p2Go(''); await sleep(30);
  c('PC：計画シートを1画面（左＝目標・MAP・数字・改善点｜右＝4分野の行動）', !!$('.sh-pc') && $$('.sh-pc .side .sh-al').length === 4 && !!$('.sh-pc .sh-tb') && !!$('.sh-pc .sh-map svg'));
  c('PC：数字は表（先月 目標・結果｜今月 目標・進捗）', /先月/.test($('.sh-tb').textContent) && /現在の進捗/.test($('.sh-tb').textContent));
});
