// v618：今日（タイル）・再アプローチ（1画面＋人を足す）・設定（リスト→1項目ずつ）・スマホの上の帯なし
const T = require('../lib/head.js')();
const { w, c, sleep, setWH, $, $$ } = T;
T.run(async () => {
  T.login();
  const F = (id, ln, fn, t) => ({ id, lastName: ln, firstName: fn, title: t, parentId: 'r', mapType: 'both' });
  w.state.members = [{ id: 'r', lastName: '山内', firstName: '北斗', title: 'ゴールド', parentId: '', mapType: 'both' }, F('f1', '佐藤', '花', 'B1'), F('f2', '田中', '健', 'Q2'), F('f3', '鈴木', '一郎', 'B3')];
  w.state.events = [{ id: 'e1', title: '佐藤CT', date: '2026-10-14', time: '20:00', ownerUid: T.OWNER }];
  w.state.currentMonth = '2026.10';
  w._reapproach = [
    { mid: 'f2', name: '田中 健', date: '2026-06-01', month: '2026.06', memo: '転職で忙しい' },
    { mid: '', name: '木村', date: '2026-09-14', month: '2026.09', memo: '', manual: true },
  ];
  setWH(390, 844);
  w.switchView('home'); w._uxSync(); await sleep(50);
  console.log('=== ① 今日 ===');
  c('スマホは上の帯なし（ux-nh）', w.document.body.classList.contains('ux-nh'));
  c('今日のタイル（手帳・予定・今週やること・気になる人・再アプローチ）', !!$('.tdy') && $$('.tdy-t').length === 5);
  const tx = $('.tdy').textContent;
  c('手帳と予定と再アプローチの中身', tx.indexOf('今日の手帳') >= 0 && tx.indexOf('佐藤CT') >= 0 && tx.indexOf('声をかける時期が来た人') >= 0);
  const n0 = w.state.events.filter(e => e.type === 'task').length;
  w.tdyToDp('f1'); await sleep(5);
  const tk = w.state.events.filter(e => e.type === 'task' && e.title.indexOf('佐藤さん フォロー') >= 0)[0];
  c('「手帳へ」で今日の手帳にタスク', tk && tk.date === '2026-10-14' && tk.memberId === 'f1' && w.state.events.filter(e => e.type === 'task').length > n0);
  console.log('=== ② 再アプローチ ===');
  w.reapOpen(); await sleep(20);
  const rp = $('#reapPg');
  c('1つの画面で開く', !!rp && rp.textContent.indexOf('時期が来た人') >= 0 && rp.textContent.indexOf('まだ早い人') >= 0);
  const rows = $$('#reapPg .rp-r');
  c('時期が来た人（135日）が上・まだ早い人（あと60日）', rows.length === 2 && rows[0].textContent.indexOf('田中') >= 0 && rows[0].textContent.indexOf('135') >= 0 && rows[1].textContent.indexOf('あと60日') >= 0);
  c('下の帯：‹戻る・＋人を足す', $('#reapPg .ux-btm').textContent.indexOf('人を足す') >= 0);
  w.reapAddStart(); await sleep(80);
  c('足すモード：検索欄', !!$('#rpQ') && $('#reapPg .ux-btm').textContent.indexOf('やめる') >= 0);
  w.reapQ('鈴木');
  c('名前でメンバーを絞り込み＋名前だけで足す', $$('#rpLs .efr').length === 2 && $('#rpLs').textContent.indexOf('鈴木 一郎') >= 0 && $('#rpLs').textContent.indexOf('名前だけで足す') >= 0);
  w.document.activeElement && w.document.activeElement.blur && w.document.activeElement.blur();
  $('#rpMemo').value = '春に声かけ';
  w.reapAddMem('f3'); await sleep(5);
  c('メンバーを足す（今日の日付・メモ）', w._reapproach[0].mid === 'f3' && w._reapproach[0].date === '2026-10-14' && w._reapproach[0].memo === '春に声かけ' && $$('#reapPg .rp-r').length === 3);
  w.reapAddStart(); await sleep(80); w.reapQ('鈴木'); w.document.activeElement && w.document.activeElement.blur && w.document.activeElement.blur();
  w.reapAddMem('f3'); c('同じ人は二重に入らない', w._reapproach.filter(r => r.mid === 'f3').length === 1);
  w._rpAdd = null; w.reapAddStart(); await sleep(80); w.reapQ('小林さん'); w.document.activeElement && w.document.activeElement.blur && w.document.activeElement.blur();
  w.reapAddName(); await sleep(5);
  c('名前だけでも足せる', w._reapproach[0].name === '小林さん' && !w._reapproach[0].mid && w._reapproach.length === 4);
  const i0 = w._reapproach.findIndex(r => r.mid === 'f2');
  w.reapToDp(i0); await sleep(5);
  c('手帳に入れる（優先A）', w.state.events.some(e => e.type === 'task' && e.title === '田中 健 再アプローチ' && e.priority === 'high' && e.date === '2026-10-14'));
  w.reapTap(i0); await sleep(5);
  c('タップでシート（その人の画面・手帳・外す）', !!$('#rpOv') && $('#rpOv').textContent.indexOf('その人の画面') >= 0 && $('#rpOv').textContent.indexOf('リストから外す') >= 0);
  w._p2SheetClose('rpOv');
  w.reapDelete(i0); await sleep(30);
  c('外すと画面も更新', !w._reapproach.some(r => r.mid === 'f2') && !$('#reapPg').textContent.includes('田中 健'));
  w.reapClose(); c('閉じる', !$('#reapPg'));
  console.log('=== ③ 設定 ===');
  w.setOpen(); await sleep(5);
  const st = $('#setPg');
  c('設定はリスト', !!st && $$('#setPg .st-ls>div').length >= 8 && st.textContent.indexOf('翌月コピー') >= 0 && st.textContent.indexOf('毎日のいつもの行') >= 0 && st.textContent.indexOf('ログアウト') >= 0);
  w.setOpen('look'); await sleep(5);
  c('見た目のページ', $('#setPg .ux-h2').textContent === '見た目' && $('#setPg .ux-crumb').textContent.indexOf('設定') >= 0);
  const lt0 = w.document.body.classList.contains('light');
  w.setTheme(lt0 ? 'dark' : 'light'); w._stRender();
  c('テーマを切り替え（その場で反映）', w.document.body.classList.contains('light') !== lt0);
  w.setTheme(lt0 ? 'light' : 'dark');
  w.setOpen('prof'); await sleep(5);
  c('プロフィールのページ', !!$('#stName') && $('#stName').value === '山内北斗' && !!$('#stUnion'));
  let saved = 0; const sp = w.saveProfile; w.saveProfile = () => { saved++; };
  w.stSaveProf(); c('必須が空だと保存しない', saved === 0 && !!$('#stName'));
  const u = $('#stUnion'); if (u.options.length > 1) u.value = u.options[1].value;
  const a = $('#stArea'); if (a.options.length > 1) a.value = a.options[1].value;
  $('#stUpRuby').value = '山田'; $('#stUpBd').value = '佐々木'; $('#stName').value = '山内 北斗';
  w.stSaveProf();
  c('保存（今までの保存処理へ渡す）', saved === 1 && $('#profileName').value === '山内 北斗' && $('#profileUpRuby').value === '山田' && $('#setPg .ux-h2').textContent === '設定');
  w.saveProfile = sp;
  w.setClose(); c('閉じる', !$('#setPg'));
  console.log('=== ④ メニューの入口 ===');
  w.switchView('menu'); await sleep(20);
  const mh = $('#view-menu') ? $('#view-menu').innerHTML : '';
  c('メニューの再アプローチ・設定が新しい画面へ', mh.indexOf('reapOpen()') >= 0 && mh.indexOf('setOpen()') >= 0);
  console.log('=== ⑤ PC ===');
  setWH(1400, 900); w._uxSync(); w.switchView('home'); await sleep(20);
  c('PCは上の帯あり・今までのホーム', !w.document.body.classList.contains('ux-nh') && !$('.tdy'));
});
