// v715：やること（時系列・数値の目標 7/8・サブタスク・📅予定に入れる）＋計画シートの課題パネル（自分・全体のメモ／やることへ）
const T = require('../lib/head.js')();
const { w, c, sleep, setWH, $, $$ } = T;
T.run(async () => {
  T.login(); setWH(390, 844); w._uxSync && w._uxSync();
  w.state.members = [{ id: 'r', lastName: '山内', firstName: '北斗', title: 'G', parentId: '', mapType: 'both' }, { id: 'a', lastName: '井上', firstName: '花', title: 'LOI', parentId: 'r', mapType: 'both' }];
  w.switchView('plan'); w.p2Go('yk'); await sleep(30);
  const cur = w._p2Ym(0), nx = w._p2YmAdd(cur, 1);
  c('やることのページ（足す欄・今月の見出し）', !!$('.yk-add') && /（今月）/.test($('.yk').textContent));
  $('#p2YkIn').value = '本を2冊読む'; w.p2YkAdd(); await sleep(20);
  const t1 = w.state.events.find(e => e.title === '本を2冊読む');
  c('タスクを足す（自分・今月）', !!t1 && t1.yk === 1 && t1.planYm === cur && t1.who === 'me' && /本を2冊読む/.test($('.yk').textContent) && /自分/.test($('.yk-r .who').textContent));
  w._p2YkAddYm = nx; w._p2YkAddWho = 'a'; $('#p2YkIn').value = '井上さんの審査フォロー'; w.p2YkAdd(); await sleep(20);
  const t2 = w.state.events.find(e => e.title === '井上さんの審査フォロー');
  c('来月・人つきのタスク（時系列で来月の見出しの下）', t2.planYm === nx && t2.memberId === 'a' && $$('.yk-g').length >= 2 && /井上/.test($$('.yk-g')[1].textContent));
  w.p2YkTy('n'); w._p2YkAddYm = cur; w._p2YkAddWho = 'me'; await sleep(10); $('#p2YkIn').value = 'ST開催 8'; w.p2YkAdd(); await sleep(20);
  const n1 = w._p2YkN()[0];
  c('数値の目標（グラフなし・0/8）', !!n1 && n1.g === 8 && n1.t === 'ST開催' && $('.yk-r.nm .nvi').value === '0' && /\/8/.test($('.yk-r.nm .nv').textContent) && !$('.yk-r.nm .bar'));
  w.p2YkNV(n1.id, 1); w.p2YkNV(n1.id, 1); await sleep(10);
  c('＋で進める（2/8）', $('.yk-r.nm .nvi').value === '2');
  w.p2YkSubOpen('t', t1.id); await sleep(40); const sa = $('#p2YkSi'); sa.value = '1冊目'; w.p2YkSiKey({ key: 'Enter', isComposing: false, preventDefault() {} }, 't', t1.id, sa); await sleep(40);
  c('サブタスク（v734：「＋ サブタスク」で書く・0/1）', (t1.subs || []).length === 1 && /0\/1/.test($('.yk-r .sb').textContent) && !!$('#p2YkSi'));
  w.p2YkSub('t', t1.id, 0); await sleep(10);
  c('サブタスクをチェック（1/1）', t1.subs[0].dn === true && /1\/1/.test($('.yk-r .sb').textContent));
  w.p2YkCal('t', t1.id); await sleep(10); $('#p2YkPd').value = cur + '-20'; $('#p2YkPt').value = '19:00'; w.p2YkCalOk(); await sleep(20);
  const ev = w.state.events.find(e => e.type === 'event' && e.title === '本を2冊読む');
  c('📅 予定に入れる（カレンダーの予定ができる・札に日時）', !!ev && ev.date === cur + '-20' && ev.time === '19:00' && (t1.ykCal || []).indexOf(ev.id) >= 0 && /20 19:00/.test($$('.yk-r .cal.on')[0].textContent));
  w.p2YkDone(t1.id); await sleep(10);
  c('済みは隠れる（済みの数は見出しに）', !/本を2冊読む/.test($('.yk').textContent.replace(/済み.*/, '')) || !!$('.yk-gh small'));
  console.log('=== 計画シートの課題パネル ===');
  w.p2Go('sheet'); await sleep(30);
  const fi = $('.iss-fi'); c('自分・全体のメモの欄', !!fi);
  fi.value = 'ST会場を探す'; w.p2ShIssFAdd(fi); await sleep(20);
  const F = w._p2ShM(w._p2ShYmN()).issF; c('人に紐づかないメモを書ける', F.length === 1 && /自分・全体/.test($('.iss').textContent) && /ST会場を探す/.test($('.iss').textContent));
  w.p2ShIssAct('F:' + F[0].id); await sleep(10);
  c('残す先：やることへ・予定・消す', /立案へ/.test($('.iss-r .cats').textContent) && /予定/.test($('.iss-r .cats').textContent));
  w.p2ShIssFTo(F[0].id, 'yk'); await sleep(20);
  const t3 = w.state.events.find(e => e.title === 'ST会場を探す');
  c('やることへ入る（自分・この月）・印', !!t3 && t3.yk === 1 && t3.who === 'me' && /立案/.test($('.iss .lk').textContent));
  w.p2ShIssSave('a', '審査フォロー'); w.p2ShIssTo('a', 'yk'); await sleep(20);
  const t4 = w.state.events.find(e => /井上.*審査フォロー/.test(e.title) && e.yk);
  c('人の課題もやることへ（その人つき）', !!t4 && t4.memberId === 'a');
});
