// v717：年の目標・ロードマップ（①マイルストーン ②直近の目標 ③今→必要→ギャップ ④フロントのペース ⑤戦略のメモ。③の表と⑤は組織15人から）
const T = require('../lib/head.js')();
const { w, c, sleep, setWH, $, $$ } = T;
T.run(async () => {
  T.login(); setWH(390, 844); w._uxSync && w._uxSync();
  const mk = (n) => { const ms = [{ id: 'r', lastName: '山内', firstName: '北斗', title: 'ゴールド', parentId: '', mapType: 'both', ptCurrent: 3000 }]; for (let i = 0; i < n; i++) ms.push({ id: 'x' + i, lastName: '山田' + i, firstName: '太', title: i === 0 ? 'BR' : 'B1', parentId: i < 4 ? 'r' : 'x' + (i % 4), mapType: 'both' }); return ms; };
  w.state.members = mk(5); w.switchView('plan'); await sleep(30);
  const p = w.state.goals.plan; p.title = 'チームエリート'; p.deadline = w._p2YmAdd(w._p2Ym(0), 14); p.income = 3410000;
  const cur = w._p2Ym(0), dl = w._p2YmAdd(cur, 6);
  w._p2().next = { title: 'RUBY', tm: true, inc: 80, deadline: dl };
  w.switchView('plan'); w.p2Go('year'); await sleep(40);
  const tx = () => $('#view-plan').textContent;
  c('S稼働の段と4つの入口はなくした', !$('#view-plan .ux-list') && !/S稼働/.test(tx()) && /最終目標/.test($('.yr-goal').textContent));
  c('①マイルストーン：直近と最終の旗・逆算（LOI→BR）・F', /RUBY（直近）/.test($('.yr-g .fl').textContent) && /TEAM ELITE/.test($('.yr-g .fl').textContent) && $$('.yr-g .rv span').length === 5 && $$('.yr-g .rv span')[4].textContent === 'BR');
  c('組織15人未満は③の表と⑤に鍵（必要なフロントと締め切りは出す）', !$('.yr-gp') && $$('.yr-lock').length === 2 && /5人/.test($('.yr-lock').textContent) && /必要なフロント/.test($('.yr-calc').textContent));
  const C = w._p2YrCalc();
  c('必要なフロント＝足りないフロントBR×2・締め切りはLOIの月', C.needBR === 3 && C.needFr === 6 && C.dlF === w._p2YmAdd(dl, -4) && C.months.length === 3);
  w.p2YrEven(); await sleep(20);
  c('④均等に割り振る（計画シート・月の目標と同じ数字）', C.months.every(ym => w._p2FrontTgt(ym) === 2) && w._p2M(cur).front === 2 && /6 \/ 6人/.test($('.yr-psum').textContent));
  w.p2YrF(cur, 5); await sleep(20);
  c('1ヶ月5人以上は赤・「1ヶ月ずらす」', !!$('.yr-pace .ng') && !!$('.yr-warn') && /1ヶ月ずらす/.test($('.yr-warn').textContent));
  w.p2YrShift(); await sleep(20);
  c('ずらすと直近の目標の月が1ヶ月後ろに', w._p2Next().deadline === w._p2YmAdd(dl, 1) && w._p2YrCalc().months.length === 4);
  w.p2YrMo(w._p2YmAdd(cur, 2)); await sleep(20);
  c('月を押すとメニュー（イベントを書く）', !!$('#p2YrMm') && !!$('#p2YrMi'));
  $('#p2YrMi').value = 'SA早期達成'; w.p2YrMsAdd(w._p2YmAdd(cur, 2), $('#p2YrMi')); await sleep(20);
  c('イベントが線の上に旗で出る', w._p2Rm().ms.some(m => m.t === 'SA早期達成' && m.ym === w._p2YmAdd(cur, 2)) && /SA早期達成/.test($('.yr-g .fl').textContent));
  w.p2YrNearMo(w._p2YmAdd(cur, 9)); await sleep(20);
  c('月のメニューから直近の目標の月にできる', w._p2Next().deadline === w._p2YmAdd(cur, 9) && !$('#p2YrMm'));
  w.state.members = mk(16); w.renderPlan(); await sleep(30);
  c('15人から③の表（エキスパート・環境も）と⑤', !!$('.yr-gp') && /エキスパート/.test($('.yr-gp').textContent) && /環境/.test($('.yr-gp').textContent) && !$('.yr-lock') && !!$('.yr .iss-fi'));
  w.p2YrT('br', 6); await sleep(20);
  c('必要な数を直すと必要なフロントも変わる', w._p2YrCalc().needBR === 5 && w._p2YrCalc().needFr === 10);
  const fi = $('.yr .iss-fi'); fi.value = '紹介ルートを増やす'; w.p2YrMemoAdd(fi); await sleep(20);
  const mm = w._p2Yr().memo[0];
  c('⑤戦略をメモ', !!mm && /紹介ルートを増やす/.test($('.yr .iss').textContent));
  w.p2YrMemoAct(mm.id); await sleep(10); w.p2YrMemoTo(mm.id, 'yk'); await sleep(20);
  const e = w.findEvent(mm.yk);
  c('残す先：やることへ', !!e && e.yk === 1 && e.title === '紹介ルートを増やす' && /やること/.test($('.yr .iss .lk').textContent));
  setWH(1400, 900); w._uxSync && w._uxSync(); w.switchView('plan'); w.p2Go('year'); await sleep(40);
  c('PCも同じ1画面（タブ）', !!$('.yr .yr-tl') && !!$('.yr-gp'));
});
