// v724：⑤ 戦略・戦術（戦略→戦術→タスク・期日・対象者（名前で探す・複数）・数値・入れる先は後から）
const T = require('../lib/head.js')();
const { w, c, sleep, setWH, $, $$ } = T;
T.run(async () => {
  T.login(); setWH(390, 844); w._uxSync && w._uxSync();
  const ms = [{ id: 'r', lastName: '山内', firstName: '北斗', title: 'ゴールド', parentId: '', mapType: 'both' }];
  for (let i = 0; i < 16; i++) ms.push({ id: 'x' + i, lastName: '山田' + i, firstName: '太', title: 'B1', parentId: i < 4 ? 'r' : 'x' + (i % 4), mapType: 'both' });
  ms.push({ id: 'ino', lastName: '井上', firstName: '花', kana: 'いのうえ', title: 'LOI', parentId: 'r', mapType: 'both' });
  ms.push({ id: 'sa', lastName: '佐藤', firstName: '健', title: 'BM', parentId: 'r', mapType: 'both' });
  w.state.members = ms; w.switchView('plan'); await sleep(30);
  w._p2Yr().memo = [{ id: 'm1', t: '前のメモ' }];
  w.p2Go('year'); await sleep(30);
  c('前のメモは戦略に移る', w._ys().some(s => s.t === '前のメモ') && /前のメモ/.test($('.ys-c').textContent));
  w.ysAddOpen(''); await sleep(40);
  let i = $('#ysIn'); i.value = '紹介ルートを増やす'; w.ysAddDo(i, false); await sleep(20);
  const st = w._ys().find(s => s.t === '紹介ルートを増やす');
  c('戦略を書く（大きいカード）', !!st && $$('.ys-c').length === 2);
  w.ysAddOpen(st.id); await sleep(40);
  i = $('#ysIn'); c('戦略の下に「戦術を書く」', /戦術/.test(i.placeholder));
  i.value = '毎週ST2回開催'; w.ysAddDo(i, true); await sleep(30);
  i = $('#ysIn'); i.value = 'CTを月8回'; w.ysAddDo(i, false); await sleep(20);
  c('戦術を何個でも（Enterで続けて）', st.kids.length === 2);
  const tc = st.kids[0];
  w.ysAddOpen(tc.id); await sleep(40); i = $('#ysIn'); c('戦術の下に「タスクを書く」', /タスク/.test(i.placeholder));
  i.value = '井上さんにST開催を依頼'; w.ysAddDo(i, true); await sleep(30); i = $('#ysIn'); i.value = '会場を予約'; w.ysAddDo(i, false); await sleep(20);
  c('タスクも何個でも・チェックの丸', tc.kids.length === 2 && $$('.ys-r.l2 .ck').length === 2);
  const tk = tc.kids[0];
  w.ysEdit(tk.id); await sleep(30);
  c('行を押すと直す画面（期日・対象者・数値・入れる先）', !!$('.ys-sh') && !!$('.ys-sh input[type=date]') && !!$('#ysQ') && !!$('.ys-sh input.n') && !!$('.ys-sh .ys-dest'));
  w.ysSet('d', '2026-10-15'); await sleep(10);
  w.ysQ('いのう'); await sleep(10);
  c('名前で探す（ふりがなでも）', /井上/.test($('#ysRes').textContent) && !/佐藤/.test($('#ysRes').textContent));
  w.ysWho('ino'); await sleep(10); w.ysQ('佐藤'); await sleep(10); w.ysWho('sa'); await sleep(10);
  c('対象者は複数', tk.who.join() === 'ino,sa' && /井上・佐藤/.test($('.ys-r.l2').textContent) && /10\/15/.test($('.ys-r.l2').textContent));
  w.ysEdClose(); await sleep(10);
  w.ysEdit(tc.id); await sleep(20); w.ysSet('n', '8'); w.ysSet('u', '回'); w.ysEdClose(); await sleep(10);
  c('数値が出る', /8回/.test($$('.ys-r.l1')[0].textContent));
  c('入れるまではどこにも入らない', !w.state.events.some(e => e.title === '井上さんにST開催を依頼'));
  w.ysAct(tk.id); await sleep(10);
  c('→ 入れる先：やること・計画シートの4分野・予定・メンバーのメモ', $$('.ys-dest span').length === 7);
  w.ysTo(tk.id, 'act:front'); await sleep(20);
  const ea = w.findEvent(tk.L.id);
  c('計画シートの行動へ（期日の月・対象者つき）', ea.planCat === 'front' && ea.planYm === '2026-10' && ea.date === '2026-10-15' && ea.memberIds.join() === 'ino,sa' && /フロント作り/.test($('.ys-r.l2 .b').textContent));
  w.ysTo(tc.id, 'yk'); await sleep(20);
  const n = w._p2YkN().find(x => x.id === tc.L.id);
  c('数値のある戦術→やることの数値の目標（0/8）', !!n && n.g === 8 && /0\/8/.test($('.ys-r.l1 .b').textContent));
  w.ysDn(tk.id); await sleep(20);
  c('チェックすると入れた先も済み・戦略にタスクの進み', ea.done === true && /タスク 1\/2/.test($$('.ys-r.l0 > .ln .rt').find(x => x.closest('.ys-c').textContent.indexOf('紹介ルート') >= 0).textContent));
  w.ysEdit(tk.id); await sleep(10); w.ysSet('t', '井上さんにST開催を頼む'); w.ysEdClose(); await sleep(10);
  c('済んだ行動の文は変えない（済んでない時だけ一緒に直る）', ea.title === '井上さんにST開催を依頼');
  w.ysEdit(tc.kids[1].id); await sleep(10); w.ysSet('t', '会場を2つ予約'); await sleep(10);
  w.ysTo(tc.kids[1].id, 'yk'); await sleep(10); const ey = w.findEvent(tc.kids[1].L.id); w.ysSet('t', '会場を3つ予約'); await sleep(10);
  c('入れた後に直すと、入れた先も直る', ey.title === '会場を3つ予約');
  w.ysEdClose(); w.ysEdit(st.id); await sleep(10); w.confirm = () => true; w.ysDel(); await sleep(10);
  c('消す（下も消える・入れた先は残る）', !w._ys().some(s => s.id === st.id) && !!w.findEvent(ea.id));
});
